apiVersion: email.example.com/v1
kind: EmailSenderConfig
metadata:
  labels:
    app.kubernetes.io/name: emailsenderconfig-mailersend
    app.kubernetes.io/instance: emailsenderconfig-sample
    app.kubernetes.io/part-of: k8s-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-operator
  name: emailsenderconfig-mailersend
spec:
  provider: mailersend
  apiTokenSecretRef: mailersend-token
  senderEmail: operator@trial-o65qngkk683gwr12.mlsender.net
