apiVersion: email.example.com/v1
kind: Email
metadata:
  labels:
    app.kubernetes.io/name: email
    app.kubernetes.io/instance: email-sample
    app.kubernetes.io/part-of: k8s-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-operator
  name: email-sample-mailersend
spec:
  senderConfigRef: emailsenderconfig-mailersend
  recipientEmail: garces.g1999@gmail.com
  subject: test-subject
  body: test-body
